services:
  app:
    image: ghcr.io/basketikun/infinite-canvas:latest
    container_name: "${CONTAINER_NAME}"
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      ANALYTICS_GA4_ID: "${ANALYTICS_GA4_ID}"
      ANALYTICS_BAIDU_ID: "${ANALYTICS_BAIDU_ID}"
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
